-- MySQL Script generated by MySQL Workbench
-- Sat Nov 25 14:43:12 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema incident-reporting-system
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `incident-reporting-system` ;

-- -----------------------------------------------------
-- Schema incident-reporting-system
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `incident-reporting-system` ;
USE `incident-reporting-system` ;

-- -----------------------------------------------------
-- Table `incident-reporting-system`.`technical`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`technical` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`technical` (
  `id` BINARY(16) NOT NULL,
  `technical_name` VARCHAR(60) NOT NULL,
  `means_notification` VARCHAR(20) NOT NULL DEFAULT "Email",
  `number_incidents_resolved` INT NOT NULL DEFAULT 0,
  `incident_resolution_speed` BIGINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`specialty` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`specialty` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `specialty_name` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `specialty_name_UNIQUE` (`specialty_name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`technical__specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`technical__specialty` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`technical__specialty` (
  `fk_ts_technical` BINARY(16) NOT NULL,
  `fk_ts_specialty` BIGINT NOT NULL,
  INDEX `fk_ts_technical` (`fk_ts_technical` ASC) VISIBLE,
  INDEX `fk_ts_specialty` (`fk_ts_specialty` ASC) VISIBLE,
  CONSTRAINT `fk_ts_technical`
    FOREIGN KEY (`fk_ts_technical`)
    REFERENCES `incident-reporting-system`.`technical` (`id`),
  CONSTRAINT `fk_ts_specialty`
    FOREIGN KEY (`fk_ts_specialty`)
    REFERENCES `incident-reporting-system`.`specialty` (`id`));


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`service` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`service` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `service_name` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`client` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`client` (
  `id` BINARY(16) NOT NULL,
  `cuit` VARCHAR(11) NOT NULL,
  `service` VARCHAR(18) NOT NULL,
  `business_name` VARCHAR(80) NOT NULL,
  `fk_service_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `business_name_UNIQUE` (`business_name` ASC) VISIBLE,
  UNIQUE INDEX `cuit_UNIQUE` (`cuit` ASC) VISIBLE,
  INDEX `fk_client_service1_idx` (`fk_service_id` ASC) VISIBLE,
  CONSTRAINT `fk_client_service`
    FOREIGN KEY (`fk_service_id`)
    REFERENCES `incident-reporting-system`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`type_problem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`type_problem` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`type_problem` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `type_problem_name` VARCHAR(45) NOT NULL,
  `maximum_resolution_time` BIGINT NOT NULL,
  `stimated_resolution_time` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `type_problem_name_UNIQUE` (`type_problem_name` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`type_problem__specialty`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`type_problem__specialty` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`type_problem__specialty` (
  `fk_tps_type_problem` BIGINT NOT NULL,
  `fk_tps_specialty` BIGINT NOT NULL,
  INDEX `fk_tps_type_problem` (`fk_tps_type_problem` ASC) VISIBLE,
  INDEX `fk_tps_specialty` (`fk_tps_specialty` ASC) VISIBLE,
  CONSTRAINT `fk_tps_type_problem`
    FOREIGN KEY (`fk_tps_type_problem`)
    REFERENCES `incident-reporting-system`.`type_problem` (`id`),
  CONSTRAINT `fk_tps_specialty`
    FOREIGN KEY (`fk_tps_specialty`)
    REFERENCES `incident-reporting-system`.`specialty` (`id`));


-- -----------------------------------------------------
-- Table `incident-reporting-system`.`incident`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `incident-reporting-system`.`incident` ;

CREATE TABLE IF NOT EXISTS `incident-reporting-system`.`incident` (
  `id` BINARY(16) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `considerations` VARCHAR(255) NOT NULL,
  `fk_technical_id` BINARY(16) NOT NULL,
  `fk_client_id` BINARY(16) NOT NULL,
  `resolved` TINYINT NOT NULL,
  `fk_type_problem_id` BIGINT NOT NULL,
  `create_time` TIMESTAMP NOT NULL,
  `time_is_up` TIMESTAMP NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_incident_technical` (`fk_technical_id` ASC) VISIBLE,
  INDEX `fk_client_id_idx` (`fk_client_id` ASC) VISIBLE,
  INDEX `fk_incident_type_problem_id_idx` (`fk_type_problem_id` ASC) VISIBLE,
  CONSTRAINT `fk_incident_technical`
    FOREIGN KEY (`fk_technical_id`)
    REFERENCES `incident-reporting-system`.`technical` (`id`),
  CONSTRAINT `fk_incident_client`
    FOREIGN KEY (`fk_client_id`)
    REFERENCES `incident-reporting-system`.`client` (`id`),
  CONSTRAINT `fk_incident_type_problem_id`
    FOREIGN KEY (`fk_type_problem_id`)
    REFERENCES `incident-reporting-system`.`type_problem` (`id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
